### ISSUE TITLE
timeliner.Timeliner not working

### ISSUE THREAD

**Issue by mewph** [LDO-CERT/orochi#1097]
When using timerliner.Timeliner plugin Orochi throws the follwing error:

`Traceback (most recent call last): File "/app/orochi/utils/volatility_dask_elk.py", line 453, in run_plugin runned_plugin = constructed.run() ^^^^^^^^^^^^^^^^^ File "/src/volatility3/volatility3/framework/plugins/timeliner.py", line 259, in run plugin = plugins.construct_plugin( ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/src/volatility3/volatility3/framework/plugins/__init__.py", line 62, in construct_plugin constructed = plugin( ^^^^^^^ File "/src/volatility3/volatility3/framework/interfaces/plugins.py", line 129, in __init__ super().__init__(context, config_path) File "/src/volatility3/volatility3/framework/interfaces/configuration.py", line 678, in __init__ super().__init__() File "/src/volatility3/volatility3/framework/interfaces/configuration.py", line 810, in __init__ framework.require_interface_version(*self._required_framework_version) File "/src/volatility3/volatility3/framework/__init__.py", line 65, in require_interface_version raise RuntimeError( RuntimeError: Framework interface version 2.5 is an older revision than the required version 2.6`

**Comment by dadokkio** [comment]
Hello, when updating volatility I forgot to update also it's relative __init__.py 
I just add a minor 2.2.2 release to address this issue.
