### ISSUE TITLE
dask worker issue on docker swarm with new image

### ISSUE THREAD

**Issue by garanews** [LDO-CERT/orochi#249]
new dask Dockerfile will use

``` FROM daskdev/dask:2021.2.0 ```

instead old
 ``` FROM continuumio/miniconda3:4.8.2 ```

seems have issue when running on swarm:
```
+ echo 'no environment.yml',
+ '[' '' ']',
no environment.yml,
+ '[' '' ']',
+ exec dask-worker --preload /opt/daskworkerinit.py --nthreads 1 --nprocs 4 --memory-limit 3G tcp://scheduler:8786,
distributed.utils - INFO - Reload module daskworkerinit from .py file,
Traceback (most recent call last):,
  File "/opt/conda/bin/dask-worker", line 11, in <module>,
    sys.exit(go()),
  File "/opt/conda/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 465, in go,
    main(),
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__,
    return self.main(*args, **kwargs),
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 781, in main,
    with self.make_context(prog_name, args, **extra) as ctx:,
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 700, in make_context,
    self.parse_args(ctx, args),
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1048, in parse_args,
    value, args = param.handle_parse_result(ctx, opts, args),
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1630, in handle_parse_result,
    value = invoke_param_callback(self.callback, ctx, self, value),
    value = invoke_param_callback(self.callback, ctx, self, value),
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 123, in invoke_param_callback,
    return callback(ctx, param, value),
  File "/opt/conda/lib/python3.8/site-packages/distributed/preloading.py", line 37, in validate_preload_argv,
    preload_modules = {,
  File "/opt/conda/lib/python3.8/site-packages/distributed/preloading.py", line 38, in <dictcomp>,
    name: _import_module(name),
  File "/opt/conda/lib/python3.8/site-packages/distributed/preloading.py", line 103, in _import_module,
    module = import_file(name)[0],
  File "/opt/conda/lib/python3.8/site-packages/distributed/utils.py", line 1005, in import_file,
    loaded.append(importlib.reload(importlib.import_module(name))),
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module,
    return _bootstrap._gcd_import(name[level:], package, level),
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import,
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load,
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked,
ModuleNotFoundError: No module named 'daskworkerinit',
    loaded.append(importlib.reload(importlib.import_module(name))),
  File "/opt/conda/lib/python3.8/site-packages/distributed/utils.py", line 1005, in import_file,
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module,
    loaded.append(importlib.reload(importlib.import_module(name))),
    return _bootstrap._gcd_import(name[level:], package, level),
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import,
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 123, in invoke_param_callback,
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load,
    return callback(ctx, param, value),
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module,
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked,
    return _bootstrap._gcd_import(name[level:], package, level),
  File "/opt/conda/lib/python3.8/site-packages/distributed/preloading.py", line 37, in validate_preload_argv,
ModuleNotFoundError: No module named 'daskworkerinit',
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import,
    preload_modules = {,
  File "/opt/conda/lib/python3.8/site-packages/distributed/preloading.py", line 38, in <dictcomp>,
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load,
    name: _import_module(name),
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked,
ModuleNotFoundError: No module named 'daskworkerinit',
  File "/opt/conda/lib/python3.8/site-packages/distributed/preloading.py", line 103, in _import_module,
    module = import_file(name)[0],
  File "/opt/conda/lib/python3.8/site-packages/distributed/utils.py", line 1005, in import_file,
    loaded.append(importlib.reload(importlib.import_module(name))),
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module,
    return _bootstrap._gcd_import(name[level:], package, level),
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import,
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load,
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked,
ModuleNotFoundError: No module named 'daskworkerinit',
```

need investigate

**Comment by garanews** [comment]
moving daskworkerinit.py out of /tmp seems solve issue as did https://github.com/LDO-CERT/orochi/pull/246
